---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ks-podinfo
  namespace: acc
spec:
  interval: 5m0s
  path: ./tenants/kla/acc
  prune: true
  serviceAccountName: flux-reconciler
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
  targetNamespace: acc