apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
namespace: kla-acc
configMapGenerator:
- behavior: merge
  files:
  - files/values.yaml
  name: helmrelease-values-acc
configurations:
- kustomizeconfig.yaml