apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- behavior: create
  files:
  - files/values.yaml
  name: helmrelease-values-default
  options:
    disableNameSuffixHash: true
configurations:
- kustomizeconfig.yaml