global:
  imagePullSecrets:
  - name: credentials-container-registry-ccs
  imageRegistry: ccscicd.azurecr.io
db-configurator:
  enabled: true
  configMapEnvRefs:
    - name: endpoint-db-wm
    - name: endpoint-db-attachment
    - name: endpoint-db-cache
    - name: endpoint-db-cs
    - name: endpoint-db-events
    - name: endpoint-db-ewih
    - name: endpoint-db-rcip
    - name: endpoint-db-questionnaire
    - name: endpoint-db-drs
    - name: endpoint-db-ds
    - name: endpoint-db-productconfigurator
  secretEnvRefs:
    - name: credentials-db-wm
    - name: credentials-db-attachment
    - name: credentials-db-cache
    - name: credentials-db-cs
    - name: credentials-db-events
    - name: credentials-db-ewih
    - name: credentials-db-rcip
    - name: credentials-db-questionnaire
    - name: credentials-db-drs
    - name: credentials-db-ds
    - name: credentials-db-productconfigurator
db-initializer:
  enabled: true
  configMapEnvRefs:
    - name: endpoint-db-wm
    - name: endpoint-db-ewih
  secretEnvRefs:
    - name: credentials-db-wm
    - name: credentials-db-ewih
universal-messaging:
  enabled: true
  nameOverride: um
  configMapEnvRefs:
    - name: endpoint-um
universal-messaging-configurator:
  enabled: true
  nameOverride: um-configurator
  configMapEnvRefs:
    - name: endpoint-um
integration-server:
  enabled: true
  nameOverride: is
  resources:
    requests:
      memory: 12Gi
    limits:
      memory: 16Gi
  keySecrets:
    name: keystore-is
    mountPath: "/opt/softwareag/common/conf"
  configMapEnvRefs:
    - name: endpoint-db-wm
    - name: endpoint-db-cache
    - name: endpoint-db-cs
    - name: endpoint-db-ewih
    - name: endpoint-db-questionnaire
    - name: endpoint-db-questionnaire-read
    - name: endpoint-um
    - name: endpoint-ip-ldap
    - name: endpoint-db-drs
    - name: endpoint-db-ds
    - name: endpoint-db-ds-read
    - name: endpoint-db-productconfigurator
  secretEnvRefs:
    - name: credentials-is
    - name: credentials-db-wm
    - name: credentials-db-cache
    - name: credentials-db-cs
    - name: credentials-db-ewih
    - name: credentials-db-questionnaire
    - name: credentials-db-questionnaire-read
    - name: credentials-ip-ldap
    - name: credentials-db-drs
    - name: credentials-db-ds
    - name: credentials-db-ds-read
    - name: credentials-db-productconfigurator
  envs:
    - name: DISABLED_PACKAGES
      value: RI_Level_v121,RI_Level_v133,RI_Level_v143,RI_Level_v144,RI_Level_v152,RI_Level_v153
    - name: WS_CONS_EWIHHTTP_HOST
      value: kla-dev-ewih-service
    - name: WS_CONS_EWIHHTTP_PORT
      value: "9081"
    - name: GV_CUSTOMBACKENDS_USEHTTPALIASES
      value: "true"
    - name: MWS_HOST
      value: kla-dev-mws
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/whitelist-source-range: "80.95.163.20,149.146.5.85,193.172.150.192/26,91.240.70.5,183.82.112.139,182.73.163.98,34.91.89.124"
      # 80.95.163.20       = guida-office
      # 149.146.5.85       = guida vpn
      # 193.172.150.192/26 = ccs office
      # 91.240.70.5        = 7bulls
      # 183.82.112.139     = comakeit-primary
      # 182.73.163.98      = comakeit-backup
      # 34.91.89.124       = Guida monitoring
    hosts:
      - host: is.kla-dev.dev-1.dip.ccs.nl
        paths:
          - path: /
            pathType: Prefix
            backend:
              servicePort: 5555
    tls:
      - hosts:
          - is.kla-dev.dev-1.dip.ccs.nl
        secretName: is-tls
my-webmethods-server:
  enabled: true
  configMapEnvRefs:
    - name: endpoint-db-wm
    - name: endpoint-um
    - name: endpoint-is
    - name: endpoint-ip-ldap
  secretEnvRefs:
    - name: credentials-db-wm
    - name: credentials-um
    - name: credentials-is
    - name: credentials-ip-ldap
  service:
    port: 8585
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/whitelist-source-range: "80.95.163.20,149.146.5.85,193.172.150.192/26,91.240.70.5,183.82.112.139,182.73.163.98,34.91.89.124"
    hosts:
      - host: mws.kla-dev.dev-1.dip.ccs.nl
        paths:
          - path: /
            pathType: Prefix
            backend:
              servicePort: 8585
    tls:
      - hosts:
          - mws.kla-dev.dev-1.dip.ccs.nl
        secretName: mws-tls
api-gateway:
  enabled: true
  nameOverride: apigw
  resources:
    requests:
      memory: 12Gi
  additionalApplications:
    configMapRef: api-gateway-applications
  applicationsConfig:
    configMapRef: api-gateway-applications-config
  enabledPolicies:
    configMapRef: api-gateway-policies
  additionalJWTCertificates:
    secretMapRef: keystore-apigw
  configMapEnvRefs:
    - name: endpoint-db-ewih
    - name: endpoint-is
    - name: endpoint-ip-ldap
  secretEnvRefs:
    - name: credentials-db-ewih
    - name: credentials-ip-ldap
    - name: credentials-is
  envs:
    - name: JVM_MEM
      value: 4g
    - name: ES_HOST
      value: localhost
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/whitelist-source-range: "80.95.163.20,149.146.5.85,193.172.150.192/26,91.240.70.5,183.82.112.139,182.73.163.98,18.192.155.96,3.124.93.29"
      # 80.95.163.20       = guida-office
      # 149.146.5.85       = guida vpn
      # 193.172.150.192/26 = ccs office
      # 91.240.70.5        = 7bulls
      # 183.82.112.139     = comakeit-primary
      # 182.73.163.98      = comakeit-backup
      # 18.192.155.96      = DIP-4682 RC Connect Demo
      # 3.124.93.29        = Test Automation Server (vmas001.ccs.nl)          
    hosts:
      - host: apigw.kla-dev.dev-1.dip.ccs.nl
        paths:
          - path: /
            pathType: Prefix
            backend:
              servicePort: 9072
      - host: apigwis.kla-dev.dev-1.dip.ccs.nl
        paths:
          - path: /
            pathType: Prefix
            backend:
              servicePort: 5555
      - host: kla-dev.dev-1.dip.ccs.nl
        paths:
          - path: /
            pathType: Prefix
            backend:
              servicePort: 5555                  
    tls:
      - hosts:
          - apigw.kla-dev.dev-1.dip.ccs.nl
        secretName: apigw-tls
      - hosts:
          - apigwis.kla-dev.dev-1.dip.ccs.nl
        secretName: apigwis-tls
      - hosts:
          - kla-dev.dev-1.dip.ccs.nl
        secretName: vpdev-tls  
ewih-service:
  enabled: true
  configMapEnvRefs:
    - name: endpoint-db-ewih
    - name: endpoint-um
    - name: endpoint-is
    - name: endpoint-memcached
  secretEnvRefs:
    - name: credentials-db-ewih
    - name: credentials-um
  service:
    port: 9081
    containerPort: 9081
process-service:
  enabled: true
  resources:
    requests:
      memory: 800Mi
  configMapEnvRefs:
    - name: endpoint-db-attachment
    - name: endpoint-db-wm
    - name: endpoint-db-cs
    - name: endpoint-db-ewih
    - name: endpoint-db-events
    - name: endpoint-db-rcip
    - name: endpoint-is
    - name: endpoint-um
    - name: endpoint-memcached
  secretEnvRefs:
    - name: credentials-db-attachment
    - name: credentials-db-wm
    - name: credentials-db-cs
    - name: credentials-db-ewih
    - name: credentials-db-events
    - name: credentials-db-rcip
    - name: credentials-is
    - name: credentials-um
  service:
    port: 9092
    containerPort: 9092
ldap:
  enabled: true
  secretEnvRefs:
    - name: credentials-ip-ldap
  initConfiguration:
    secretRef: ldap-init-configuration
  additionalConfigurations:
    secretRef: ldap-configuration
  persistence:
    storageClass: redundant
memcached:
  enabled: true
kie-server:
  enabled: false
kie-workbench:
  enabled: false
